### ISSUE TITLE
[Feature] Add missing Resources/Endpoints Q1/2022

### ISSUE THREAD

**Issue by Kjarrigan** [tonobo/hcloud-ruby#24]
It's been a while since someone worked on this project so there is a bit of a gap between what you can do through the API and through this gem, so we should go through the API and check what is actually missing and then create issues to close the gaps (e.g. `LoadBalancer` are missing as well as `PlacementGroups`)

So all unchecked entries are not yet checked for differences - based on the official [docs](https://docs.hetzner.cloud/)
* [x] Actions
* [ ] Certificates **missing** #26
* [ ] Certificate Actions **missing** #26
* [x] Datacenters
* [ ] Firewalls **missing** #25
* [ ] Firewall Actions **missing** #25
* [ ] Floating IPs - **field:labels missing** #12 
* [x] Floating IP Actions
* [ ] Images - **field:labels missing** #12 
* [ ] Image Actions - **get action(s) missing** #30
* [x] ISOs
* [ ] Load Balancers **missing** #29
* [ ] Load Balancer Actions **missing** #29
* [ ] Load Balancer Types **missing** #29
* [x] Locations
* [x] Networks  - **field:labels missing** #12 #26
* [x] Network Actions **get action(s) + change_ip_range missing**
* [ ] Placement Groups **missing** #27
* [ ] Pricing **missing** #28
* [ ] Servers - **field:labels missing** #12 + **get-metrics missing**
* [ ] Server Actions - **change_dns_ptr missing** #30
* [x] Server Types
* [ ] SSH Keys - **field:labels missing** #12 
* [ ] Volumes - **field:labels missing** #12 
* [x] Volume Actions
